name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        with:
          version: '8.5.0'
          run_install: false
      - name: Install dependencies
        run: pnpm i
      - name: Lint
        run: pnpm run lint